# Generated by Django 4.1 on 2022-08-12 09:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда парсился чат')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 8, 12, 9, 40, 49, 531785, tzinfo=datetime.timezone.utc), verbose_name='Когда обновлялся')),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(max_length=200, verbose_name='Tg ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда парсился в первый раз')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 8, 12, 9, 40, 49, 532357, tzinfo=datetime.timezone.utc), verbose_name='Дата обновления')),
                ('chat', models.ManyToManyField(blank=True, related_name='hrs', to='catalog.chat', verbose_name='В каких чатах состоит')),
            ],
        ),
    ]
