# Generated by Django 4.1 on 2022-08-12 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 9, 42, 58, 161892, tzinfo=datetime.timezone.utc), verbose_name='Когда обновлялся'),
        ),
        migrations.AlterField(
            model_name='hr',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 9, 42, 58, 162475, tzinfo=datetime.timezone.utc), verbose_name='Дата обновления'),
        ),
    ]
