# Generated by Django 4.1 on 2022-08-15 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_chat_chat_id_alter_chat_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 13, 27, 22, 730378, tzinfo=datetime.timezone.utc), verbose_name='Когда обновлялся'),
        ),
        migrations.AlterField(
            model_name='hr',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 13, 27, 22, 731009, tzinfo=datetime.timezone.utc), verbose_name='Дата обновления'),
        ),
    ]
