# Generated by Django 4.1 on 2022-08-15 13:55

from django.db import migrations


def update_old_hrs(apps, schema_editor):
    HR = apps.get_model('catalog', 'HR')
    Chat = apps.get_model('catalog', 'Chat')
    new_chat = Chat.objects.get(chat_id=1917265170)
    for hr in HR.objects.all().iterator():
        hr.chat.add(new_chat)
        hr.save


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_chat_title_alter_chat_updated_at_alter_hr_updated_at'),
    ]

    operations = [
        migrations.RunPython(update_old_hrs)
    ]
