# Generated by Django 4.1 on 2022-08-17 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_chat_updated_at_alter_hr_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 8, 44, 47, 581651, tzinfo=datetime.timezone.utc), verbose_name='Когда обновлялся'),
        ),
        migrations.AlterField(
            model_name='hr',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 8, 44, 47, 582337, tzinfo=datetime.timezone.utc), verbose_name='Дата обновления'),
        ),
    ]
